import type { Metadata } from "next";
import { inknutAntiqua } from "@/app/ui/fonts";
import { Providers } from "./utils/Providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inknutAntiqua.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
