export const collections = [
  {
    id: "house-collection",
    title: "Houses Collection",
    savedListings: 10,
    collectionProperties: [
      {
        image: "/dubai.jpeg",
        _id: "1",
        propertyType: "Luxury",
        rating: 9.1,
        title: "Luxury Apartment in Dubai",
        location: "Dubai, UAE",
        bedrooms: 4,
        bathrooms: 3,
        price: 150000,
      },
      {
        image: "/high-rise.jpeg",
        _id: "2",
        propertyType: "Modern",
        rating: 8.7,
        title: "High-Rise Condo",
        location: "New York, USA",
        bedrooms: 3,
        bathrooms: 2,
        price: 120000,
      },
      {
        image: "/living-room2.jpeg",
        _id: "2",
        propertyType: "Cozy",
        rating: 8.5,
        title: "Cozy Living Room",
        location: "Paris, France",
        bedrooms: 2,
        bathrooms: 1,
        price: 90000,
      },
      {
        image: "/living-room.jpeg",
        _id: "4",
        propertyType: "Spacious",
        rating: 8.9,
        title: "Spacious Living Room",
        location: "Berlin, Germany",
        bedrooms: 3,
        bathrooms: 2,
        price: 110000,
      },
    ],
  },
  {
    id: "villas-collection",
    title: "Villas Collection",
    savedListings: 7,
    collectionProperties: [
      {
        image: "/condo.jpg",
        _id: "1",
        propertyType: "Luxury",
        rating: 9.0,
        title: "Luxury Condo",
        location: "Los Angeles, USA",
        bedrooms: 4,
        bathrooms: 3,
        price: 140000,
      },
      {
        image: "/duplex.jpg",
        _id: "1",
        propertyType: "Modern",
        rating: 8.6,
        title: "Modern Duplex",
        location: "Toronto, Canada",
        bedrooms: 3,
        bathrooms: 2,
        price: 130000,
      },
      {
        image: "/estate.jpg",
        _id: "1",
        propertyType: "Estate",
        rating: 9.2,
        title: "Sprawling Estate",
        location: "Cape Town, South Africa",
        bedrooms: 5,
        bathrooms: 4,
        price: 200000,
      },
      {
        image: "/villa.jpg",
        _id: "1",
        propertyType: "Villa",
        rating: 8.8,
        title: "Beachside Villa",
        location: "Malibu, USA",
        bedrooms: 4,
        bathrooms: 3,
        price: 160000,
      },
    ],
  },
  {
    id: "apartment",
    title: "Apartment",
    savedListings: 9,
    collectionProperties: [
      {
        image: "/apartment.jpg",
        _id: "1",
        propertyType: "Urban",
        rating: 8.4,
        title: "Urban Apartment",
        location: "Tokyo, Japan",
        bedrooms: 2,
        bathrooms: 1,
        price: 100000,
      },
      {
        image: "/bed.jpeg",
        _id: "1",
        propertyType: "Cozy",
        rating: 8.2,
        title: "Cozy Bedroom",
        location: "Amsterdam, Netherlands",
        bedrooms: 1,
        bathrooms: 1,
        price: 80000,
      },
      {
        image: "/skyscraper.jpg",
        _id: "1",
        propertyType: "Modern",
        rating: 8.9,
        title: "Modern Skyscraper",
        location: "Shanghai, China",
        bedrooms: 3,
        bathrooms: 2,
        price: 130000,
      },
      {
        image: "/street.jpg",
        _id: "1",
        propertyType: "Historic",
        rating: 8.1,
        title: "Historic Street View",
        location: "Rome, Italy",
        bedrooms: 2,
        bathrooms: 1,
        price: 95000,
      },
    ],
  },
];
