const cards = [
    {
      image: "/house1.jpg",
      category: "House",
      rating: 9.8,
      title: "Relaxing retreat at the heart of Yuba City",
      location: "Lagos, State.",
      bedrooms: 3,
      bathrooms: 4,
      price: 100000,
    },
    {
      image: "/house2.jpg",
      category: "Apartment",
      rating: 8.5,
      title: "Modern apartment with city view",
      location: "Abuja, State.",
      bedrooms: 2,
      bathrooms: 2,
      price: 80000,
    },
    {
      image: "/house3.jpg",
      category: "Cottage",
      rating: 9.2,
      title: "Cozy cottage near the beach",
      location: "Calabar, State.",
      bedrooms: 4,
      bathrooms: 3,
      price: 120000,
    },
    {
      image: "/house4.jpg",
      category: "Villa",
      rating: 9.9,
      title: "Luxurious villa with private pool",
      location: "Lekki, Lagos.",
      bedrooms: 5,
      bathrooms: 6,
      price: 250000,
    },
    {
      image: "/house5.jpg",
      category: "Studio",
      rating: 8.0,
      title: "Compact studio in the city center",
      location: "Ikeja, Lagos.",
      bedrooms: 1,
      bathrooms: 1,
      price: 50000,
    },
    {
      image: "/house6.jpg",
      category: "Bungalow",
      rating: 7.5,
      title: "Simple bungalow in the countryside",
      location: "Ibadan, Oyo.",
      bedrooms: 2,
      bathrooms: 1,
      price: 40000,
    },
    {
      image: "/house7.jpg",
      category: "Mansion",
      rating: 9.7,
      title: "Exclusive mansion with large garden",
      location: "Victoria Island, Lagos.",
      bedrooms: 6,
      bathrooms: 8,
      price: 500000,
    },
    {
      image: "/house8.jpg",
      category: "Penthouse",
      rating: 8.9,
      title: "Modern penthouse with ocean view",
      location: "Banana Island, Lagos.",
      bedrooms: 3,
      bathrooms: 4,
      price: 300000,
    },
    {
      image: "/house9.jpg",
      category: "Cabin",
      rating: 8.3,
      title: "Rustic cabin in the mountains",
      location: "Jos, Plateau.",
      bedrooms: 3,
      bathrooms: 2,
      price: 70000,
    },
    // {
    //   image: "/house10.jpg",
    //   category: "Duplex",
    //   rating: 8.7,
    //   title: "Spacious duplex with private garden",
    //   location: "Surulere, Lagos.",
    //   bedrooms: 4,
    //   bathrooms: 5,
    //   price: 150000,
    // },
    // {
    //   image: "/house11.jpg",
    //   category: "Houseboat",
    //   rating: 9.0,
    //   title: "Floating houseboat on the river",
    //   location: "Port Harcourt, Rivers.",
    //   bedrooms: 2,
    //   bathrooms: 2,
    //   price: 120000,
    // },
    // {
    //   image: "/house12.jpg",
    //   category: "Condo",
    //   rating: 8.2,
    //   title: "Luxury condo in the business district",
    //   location: "Ikeja, Lagos.",
    //   bedrooms: 3,
    //   bathrooms: 3,
    //   price: 200000,
    // },
    // {
    //   image: "/house13.jpg",
    //   category: "Farmhouse",
    //   rating: 7.8,
    //   title: "Peaceful farmhouse surrounded by greenery",
    //   location: "Abeokuta, Ogun.",
    //   bedrooms: 4,
    //   bathrooms: 3,
    //   price: 60000,
    // },
    // {
    //   image: "/house14.jpg",
    //   category: "Loft",
    //   rating: 8.6,
    //   title: "Trendy loft in a vibrant neighborhood",
    //   location: "Yaba, Lagos.",
    //   bedrooms: 2,
    //   bathrooms: 2,
    //   price: 90000,
    // },
    // {
    //   image: "/house15.jpg",
    //   category: "Chalet",
    //   rating: 9.3,
    //   title: "Beautiful chalet with mountain views",
    //   location: "Obudu, Cross River.",
    //   bedrooms: 3,
    //   bathrooms: 2,
    //   price: 100000,
    // },
    // {
    //   image: "/house16.jpg",
    //   category: "Terrace",
    //   rating: 7.9,
    //   title: "Charming terrace house with balcony",
    //   location: "Benin City, Edo.",
    //   bedrooms: 3,
    //   bathrooms: 3,
    //   price: 80000,
    // },
    // {
    //   image: "/house17.jpg",
    //   category: "Townhouse",
    //   rating: 8.4,
    //   title: "Family-friendly townhouse in a gated estate",
    //   location: "Owerri, Imo.",
    //   bedrooms: 4,
    //   bathrooms: 4,
    //   price: 140000,
    // },
    // {
    //   image: "/house18.jpg",
    //   category: "Tiny House",
    //   rating: 8.1,
    //   title: "Cozy tiny house with smart design",
    //   location: "Enugu, Enugu.",
    //   bedrooms: 1,
    //   bathrooms: 1,
    //   price: 45000,
    // },
    // {
    //   image: "/house19.jpg",
    //   category: "Castle",
    //   rating: 9.5,
    //   title: "Historic castle with breathtaking views",
    //   location: "Kano, Kano.",
    //   bedrooms: 10,
    //   bathrooms: 12,
    //   price: 1000000,
    // },
    // {
    //   image: "/house20.jpg",
    //   category: "RV",
    //   rating: 7.6,
    //   title: "Fully equipped RV for road trips",
    //   location: "Ilorin, Kwara.",
    //   bedrooms: 1,
    //   bathrooms: 1,
    //   price: 35000,
    // },
  ];
  
  export default cards;
  